Created a Team page.
STAC-IITMandi/STAC-IITMandi.github.io pull request #161
Opened 2020-12-07 22:34 UTC by tusharrao198

1. Added a database model for team members which can be used to edit, add or update the information. 
2. Also added some media roots form images in settings.py file . 
3. Registered Models in order to access them from django-admin.
4. Added  Images shown on team page can now be shown ordered batchwise. 
5. Information about the links can be added later.

2020-12-08 04:04 UTC, LalitNM commented
@tusharrao198 you need to rebase your branch.

2020-12-08 05:48 UTC, gajrajgchouhan commented
You should use different branches for different PRs.

2020-12-08 06:45 UTC, tusharrao198 commented
> You should use different branches for different PRs, and do `git pull` before you start commiting to make sure your `clone` is up-to-date.

Yeah i did that but the previous PR was not merged until then. That why the rebase issue.

2020-12-08 10:20 UTC, harnaman-hk commented
@tusharrao198  Can you attach a screenshot of how it looks on the frontend?

2020-12-08 10:40 UTC, tusharrao198 commented
Ok

2020-12-08 12:07 UTC, tusharrao198 commented
![vlcsnap-2020-12-08-17h33m48s522](https://user-images.githubusercontent.com/56690827/101481819-c099d600-397b-11eb-800a-35c755a9d614.png)

2020-12-08 17:42 UTC, tusharrao198 commented
1. Readme added for steps to add user through admin page. 
2. Directly add a member and his/her photo.
3. Batch column created in order to show images of the core team members  on the basis of Batch ( Badelog on the top) 
@harnaman-hk  , @gajrajgchouhan

2020-12-09 04:52 UTC, gajrajgchouhan requested changes

2020-12-09 04:52 UTC, gajrajgchouhan commented on src/web_main/settings.py
> +#stac_iitmandi\static\stac_iitmandi\images
This comment can be removed.

2020-12-09 10:53 UTC, tusharrao198 commented on src/web_main/settings.py
> +#stac_iitmandi\static\stac_iitmandi\images
ok

2020-12-09 14:41 UTC, tusharrao198 commented
Issue #162 resolved in last commit.

2020-12-09 17:38 UTC, tusharrao198 commented
![image](https://user-images.githubusercontent.com/56690827/101665616-346ada00-3a73-11eb-9b11-912fefd7face.png)
![image](https://user-images.githubusercontent.com/56690827/101665680-4cdaf480-3a73-11eb-9d14-d78cc7926cc5.png)

2020-12-09 17:40 UTC, tusharrao198 commented
![image](https://user-images.githubusercontent.com/56690827/101665919-96c3da80-3a73-11eb-9b5c-9d255674db35.png)

![image](https://user-images.githubusercontent.com/56690827/101665839-80b61a00-3a73-11eb-850d-d1d637bd7f9a.png)

2020-12-09 17:54 UTC, gajrajgchouhan commented
Thank you for the PR 🚀 !!

2020-12-09 17:54 UTC, gajrajgchouhan approved these changes

2020-12-10 07:13 UTC, LalitNM commented
I strongly recommend that you put readme file in a directory with name `README.md` (in a directory where the contributor needs to set the database). Rest everything looks good :clap:

2020-12-10 07:14 UTC, LalitNM approved these changes

2020-12-10 08:42 UTC, merged